deploy: 
    stage: deploy
    only:
      - master
    script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev ./ ./arundelstrings.org  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"